config:
    environment:               development
    database_name:             wordpress
    database_user:             root
    database_password:         ~
    database_host:             localhost
    database_prefix:           ~
    database_character_set:    utf8
    database_collation:        ~
    wordpress_locale:          en_US
    wordpress_site_url:        http://localhost